# Redirects
[[redirects]]
from = "/assets/cv.pdf"
to = "/cv"
status = 301

[[redirects]]
from = "/cv.html"
to = "/cv"
status = 301

[[redirects]]
from = "/contact.html"
to = "/contact"
status = 301

[[redirects]]
from = "/index.html"
to = "/index.html"
status = 301

[[redirects]]
from = "/index.php"
to = "/index.html"
status = 301

# Pages
[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/portfolio"
to = "/index.html"
status = 200

[[redirects]]
from = "/cv"
to = "/index.html"
status = 200

[[redirects]]
from = "/contact"
to = "/index.html"
status = 200

# Public assets directory
[[redirects]]
from = "/assets/Curriculum-vitae–R.Cavdar.pdf"
to = "/assets/Curriculum-vitae–R.Cavdar.pdf"
status = 200

# 404
[[redirects]]
from = "/*"
to = "/index.html"
status = 404