# Redirects
[[redirects]]
from = "/assets/cv.pdf"
to = "/cv"
status = 301

[[redirects]]
from = "/cv.html"
to = "/cv"
status = 301

[[redirects]]
from = "/contact.html"
to = "/contact"
status = 301

[[redirects]]
from = "/index.php"
to = "/"
status = 301

[[redirects]]
from = "/favicon.ico"
to = "/assets/img/logo.png"
status = 301

# Pages
[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/portfolio"
to = "/index.html"
status = 200

[[redirects]]
from = "/cv"
to = "/index.html"
status = 200

[[redirects]]
from = "/contact"
to = "/index.html"
status = 200

# Public assets directory
[[redirects]]
from = "/assets/Curriculum-vitae–R.Cavdar.pdf"
to = "/assets/Curriculum-vitae–R.Cavdar.pdf"
status = 200

[[redirects]]
from = "/assets/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
to = "/assets/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
status = 200

[[redirects]]
from = "/assets/img/cover.png"
to = "/assets/img/cover.png"
status = 200

[[redirects]]
from = "/assets/img/logo.png"
to = "/assets/img/logo.png"
status = 200

# 404
[[redirects]]
from = "/*"
to = "/index.html"
status = 404

# Netlify build proceeds only if there are changes within the src directory
[build]
ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- src/"